
module.exports = {
    // CFORMAT_AN_DATE_MS: 0,
    CUPLOAD_PATH: '../Developer/UPLOAD',

    CJENIS_FILTER_TANGGAL: 0,
    CJENIS_FILTER_INT: 1,
    CJENIS_FILTER_STRING: 2,
    CJENIS_FILTER_DOUBLE: 3,
    CJENIS_FILTER_LIST_INT: 4,
    CJENIS_FILTER_LOOKUP: 5,

    CCODE_BERHASIL: 1,
    CCODE_GAGAL: 0,
    CSTATUS_BERHASIL: 1,
    CSTATUS_GAGAL: 0,
    CSTATUS_TIDAK_ADA_DATA: 2,

    CSTATUS_REPRINT: 6,

    CJENIS_AN_CUSTOME: -1,
    CJENIS_AN_ALL: 0,
    CJENIS_AN_HARIAN: 3,
    CJENIS_AN_BULANAN: 2,
    CJENIS_AN_TAHUNAN: 1,
    CJENIS_AN_TGL_JAM: 4,

    CSTATUS_BOOKING: 1,
}